spring:
  profiles:
    active: loadInitialData

---
spring:
  datasource:
    url: jdbc:h2:mem:fitnessdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: loadInitialData
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

---
server:
  port: 8081

